### ISSUE TITLE
ErrorException in TypeHelperTrait.php line 79

### ISSUE THREAD

**Issue by abzBear** [dkd/php-cmis-client#1]
I'm getting this error when uploading a document and only for Windows based p.c's when I do this with a Mac or Linux machine then it's ok.

Given value is of type "integer" but a value of type "double" was expected. Value has been casted to the expected type.

In the TypeHelperTrait.php class
 trigger_error(
                sprintf(
                    'Given value is of type "%s" but a value of type "%s" was expected.'
                    . ' Value has been casted to the expected type.',
                    gettype($value),
                    $expectedType
                ),
                E_USER_NOTICE
            );

My work around for now is to change the trigger_error to a  \Log::warning as i feel that it's not really an error but merely a message to display.

**Comment by sascha-egerer** [comment]
The problem has nothing todo with windows or mac/linux but your php configuration. 
Is there any reason why you use error logging for notices? If you change your php configuration to not handle notices as errors you can fix thtat problem. Not sure if you should change that here.

But to be honost: we have the same probelm whith unit tests... See b577b4889e9109c001445a537711a17fd5d12e34

So maybe we should really change that by catching this exception or not triggering an php error. But we can only do that if we have the Logger Interface in place to use something like monolog to log errors.

**Comment by abzBear** [comment]
Hi

Thanks for the reply, I haven't modified my phone configuration is the
default settings that came with want server. Let me make a change and get
back to you.

Thanks
Abdul

**Comment by sascha-egerer** [comment]
I'll close that issue now as IMHO it is not really an issue.
