### ISSUE TITLE
32-bit systems

### ISSUE THREAD

**Issue by MatthewReed** [dkd/php-cmis-client#13]
Your library has a problem in either 32 bit systems or 32-bit php install on 64-bit systems.

For example Dkd\PhpCmis\Converter\AbstractDataConverter::convertDateTimeValue tells apart integer and string values. Unfortunately in a 32-bit system timestamps with milliseconds are double and throw a CmisRuntimeException.
Equally constraints defined as integer are transformed in double and automatically converted throwing a php notice.
So I was wondering if it could be better to change library in order to address 32-bit systems ot at least add a notice in repository and throw an exception in code addressing the fact that such a library functionality is limited to 64-bit php installs.

**Comment by sascha-egerer** [comment]
Hi @MatthewReed, thank you for your report.

I think we should also be compatible to 32bit systems. 
If you have a patch feel free to open a pull request.
If not i will have a look in the next days.

**Comment by ksjogo** [comment]
Prepared a test setup on my machine, will look into it.
https://github.com/dkd/php-cmis-client/tree/32bit
Has Makefile and Dockerfile to run phpunit against 32bit

**Comment by ksjogo** [comment]
#21 is merged for the moment.
