### ISSUE TITLE
Include example of folder listing (has gist)

### ISSUE THREAD

**Issue by Mirdrack** [dkd/php-cmis-client#2]
Hello, following the suggestion of @NamelessCoder I'm opening this issue because I don't get it the idea of how to listing folder and files

My question was if I should develop another method on the Session Class implementing getChildren of NavigationService  but it seems like I'm not getting the idea of how to use the library

Maybe I just need an example of how to list folders and files but I think it will very positive have a more intuitive way to list folder and files.

Thanks in advance.

**Comment by ksjogo** [comment]
Claus is the guy to ask the questions, but you might take a look into the CMIS FAL implementation https://github.com/dkd/typo3-ext-cmis-fal meanwhile as it is working with files.

**Comment by dkd-dobberkau** [comment]
just a quick remark. the issue tracker is not a support system. As we have implemented the cmis standard 1.1 as its in the java client there might be a code explaination in the java docs of the apache chemistry project.

**Comment by sascha-egerer** [comment]
Is that what your are looking for? https://gist.github.com/sascha-egerer/0fa5d55869c0f379d9a9

As already said this implementation is oriented on the Open CMIS Implementation.

So basically every java example you find in the Web could be easily adopted as the interfaces are nearly the same.

**Comment by Mirdrack** [comment]
@dkd-dobberkau sorry for that, never was my intention take the issue board as a support panel, I only follow the suggestion of @NamelessCoder to discuss the better way to do this but now with the explanation of @sascha-egerer now is more clear the library works 
And yes.. your gist was exactly the thing i was looking for maybe its something obvious but it will be nice include this on the examples 
Thanks to everyone

**Comment by NamelessCoder** [comment]
Hi guys,

I sent @Mirdrack here not so much for support but to make sure our implementation supports the necessary usage (although it's not done via a service) and to discuss the possible need for a new method. Basically I just wanted to get Sascha's opinion but the example is even better :)

Will keep this issue open as a ticket to include Sascha's example in the examples collection!

**Comment by sascha-egerer** [comment]
I'm fine with discussing those questions here!
I'll add this gist with some comments to the examples.

**Comment by sascha-egerer** [comment]
Example has been added in phabricator and is now waiting for reviews. I've also fixed an bug that i found while extending the example.

**Comment by sascha-egerer** [comment]
Example has been added in dc31e48f9748fa1066253bb44f4c78b017728ed9
