### ISSUE TITLE
UTF-8 characters problem

### ISSUE THREAD

**Issue by della-90** [dkd/php-cmis-client#22]
Hi,

I am trying to create a document with a `UTF-8` string for property `cmis:title` (e.g., `新商品情報`).

If I set that property when I create the document through `$session->createDocument($properties, ...)` then the uploaded file has a completely wrong title (some non-printable chars).

Instead, if I first create the document with no properties and then perform an update through `$document->updateProperties(...)` everything is ok.

Is this problem related to your (or any underlying) library?

Here I attach 2 screenshots:
- What happens when I create the document with the UTF-8 title property
  ![selection_029](https://cloud.githubusercontent.com/assets/2706541/16481569/3865eb08-3eac-11e6-8f56-0bbe8efc5e3f.png)
- What happens when I create the document with no title and then update it
  ![selection_028](https://cloud.githubusercontent.com/assets/2706541/16481566/339a3174-3eac-11e6-8458-734b5ca1138b.png)

**Comment by ksjogo** [comment]
We will check.

**Comment by NamelessCoder** [comment]
This is mostly a note for myself: there could very well be a difference between the request generated from the two methods - some methods were refactored a while back to use POST method to limit the URL length for some of the larger requests. It could be a problem we introduced with that - or it could be that the request parameters are decoded differently when using GET/POST respectively.

In any case, we definitely need to check that our outgoing requests are the same from both methods!
