### ISSUE TITLE
Examples with createDocument

### ISSUE THREAD

**Issue by aivdev** [dkd/php-cmis-client#26]
I would like to see a createDocument example, similar to Apache Chemistry Library PHP.
I wont to specify content_type (for example plain /text) or...createDocument where the content is a string. For example, a plain text with contains "Hello world text".

I only see example where the user, upload a file...

Thanks.

**Comment by dkd-dobberkau** [comment]
Hi. This is a issue tracker and not a support forum.

**Comment by sascha-egerer** [comment]
@aivdev This is exactly what happens at https://github.com/dkd/php-cmis-client/blob/master/examples/CreateDocument.php#L50
You can just pass a string into the stream factory instead reading a file.
