### ISSUE TITLE
Install with composer

### ISSUE THREAD

**Issue by dj1999** [dkd/php-cmis-client#28]
Hello,

first of all thanks for this CMIS client.

I'd like to use it an Drupal 8 module and try install with composer:
$ composer require dkd/php-cmis

but it is not able:

> Using version ^1.0 for dkd/php-cmis
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Can only install one of: guzzlehttp/guzzle[5.3.x-dev, 6.2.1].
>     - Can only install one of: guzzlehttp/guzzle[6.2.1, 5.3.x-dev].
>     - Can only install one of: guzzlehttp/guzzle[6.2.x-dev, 5.3.x-dev].
>     - Can only install one of: guzzlehttp/guzzle[5.3.x-dev, 6.2.1].
>     - dkd/php-cmis v1.0.0 requires guzzlehttp/guzzle ~5.0 -> satisfiable by guzzlehttp/guzzle[5.3.x-dev].
>     - Installation request for dkd/php-cmis ^1.0 -> satisfiable by dkd/php-cmis[v1.0.0].
>     - Installation request for guzzlehttp/guzzle ^6.2.1 -> satisfiable by guzzlehttp/guzzle[6.2.1, 6.2.x-dev].
> 
> Installation failed, reverting ./composer.json to its original content.

Please let me know what is the right way to install it with composer?

**Comment by ksjogo** [comment]
We currently require guzzle 5.x, but it seems that you require guzzle 6.x somewhere in your composer.json or from another dependency. We should look into updating to Guzzle 6 though.

**Comment by dj1999** [comment]
Yes you are right. Drupal 8 core (or symphony) use guzzle version 6.2.

**Comment by ksjogo** [comment]
@NamelessCoder how much effort would be an upgrade to 6?

**Comment by NamelessCoder** [comment]
Should pretty much be a formality - if anything does need to be updated in terms of API usage we have only very few usages to update.

**Comment by NamelessCoder** [comment]
I can probably take a look at this later tonight if we want to go ahead with it!

**Comment by ksjogo** [comment]
@dkd-dobberkau - your call, I would do it from a technical perspective.

**Comment by ksjogo** [comment]
Talked with Olivier, Claus could you look into updating to 6 please.

**Comment by NamelessCoder** [comment]
Will do!

**Comment by dj1999** [comment]
Thanks for fast and positive feedback!

Please let me know where can I setting the ignoreFailures variable because if I try populating the sample repo of alfresco (https://cmis.alfresco.com/alfresco/api/-default-/public/cmis/versions/1.1/browser) get this error 

> [:error] [pid 5560] [client 127.0.0.1:36397] Uncaught PHP Exception Dkd\Populate\AccessException: "No "set" method(s) can be determined for property choice" at /home/webdev/d8-no-paragraph/modules/custom/cmis/vendor/dkd/php-populate/src/PopulateTrait.php line 266

The setPopulatedProperty function description tell:

> Sets a single property via the resolved setter method,
> throws a Dkd\Populate\Exception if no method could be found
> and $ignoreFailures was false.

but I did not found where set or where use this variable.

Thanks again!

**Comment by NamelessCoder** [comment]
@dj1999 are you using our master branch or a numbered release version? The master branch should not be affected by this error (which is caused by semantic issues with naming of the choice/choices property). See also https://github.com/dkd/php-cmis-client/commit/2605c3bbfdcb265e163c0e8165e441c4009e6623

**Comment by dj1999** [comment]
I had installed with command: composer require "dkd/php-cmis": "^1.0"
What is the recommended install process?

**Comment by NamelessCoder** [comment]
That is the recommended approach - temporarily you can switch to `dev-master` which should fix the issue. I will look into creating a new release as well.

**Comment by ksjogo** [comment]
We could do the guzzle upgrade and then tag.

**Comment by NamelessCoder** [comment]
That is my plan :) I ran into a few issues that require a new alfresco test VM so I had to delay this task until later tonight.

**Comment by dj1999** [comment]
@NamelessCoder Thanks this [https://github.com/dkd/php-cmis-client/issues/28#issuecomment-248535257] works fine.
