### ISSUE TITLE
Bearer token authentication

### ISSUE THREAD

**Issue by xunto** [dkd/php-cmis-client#29]
Is there a way to authenticate in cmis through Bearer token using this lib?

On the first look I thought that it doesn't implemented yet but maybe I can do it using Guzzle and "Authorization" header? Can somebody comment on this?

**Comment by sascha-egerer** [comment]
That should be possible if supported by guzzle. Just authenticate via
guzzle and than pass this guzzle connection into the lib. See the examples
for details.

2016-10-06 21:44 GMT+02:00 Xunto notifications@github.com:
