### ISSUE TITLE
GuzzleHttp Exception[ParseException]: Unable to parse JSON data

### ISSUE THREAD

**Issue by selva12** [dkd/php-cmis-client#31]
After configure CMIS connection i clicked the **Browse** link, then site displays "**The website encountered an unexpected error. Please try again later**". I found the error in recent logs and i enclosed error details which i am facing. Please give a solution for this.
![cmis_connection_drupal_8](https://cloud.githubusercontent.com/assets/22187608/23359542/84b03592-fc9b-11e6-8970-2f8ad8ff7dfb.png)
![d8_cmis_issue](https://cloud.githubusercontent.com/assets/22187608/23359550/91a852ac-fc9b-11e6-935c-aa9203ba7309.png)

**Comment by ksjogo** [comment]
The message is saying that it got invalid JSON from the server which should not happen and (probably) is not to be fixed on our library side (like invalid request). Which CMIS server are you using and could you look into his logs.

**Comment by selva12** [comment]
Thankyou, i will check once. I am using Alfresco 3.4.11 with drupal 8 using this CMIS module. I gave `**<root>alfresco/service/cmis**` in CMIS browser url. After saving this with login credentials i clicked the **Browse** link then only that Guzzle error(above mentioned) occurs.
I think Alfresco >5 versions are configured properly, i am not sure. So its possible to connect Alfresco 3.4.11 with this module?

**Comment by ksjogo** [comment]
Afair browser bindings were introduced with version 4.something http://ecmarchitect.com/archives/2013/09/15/3554

**Comment by selva12** [comment]
Thankyou for your info, but i need that for Alfresco 3.4 versions **not for Alfresco >4 versions**. I can able to connect 3.4.d with drupal 7 using CMIS module. Now i need to connect 3.4.d with D8. Please give solutions for that.

**Comment by ksjogo** [comment]
It seems the D8 cmis module updated to use our library for CMIS. Our library is requiring the browser bindings.
You could revert the changes in the D8 module. Or pick some other underlying lib. Or update to a newer Alfresco.

**Comment by sascha-egerer** [comment]
The implementation is very flexibale and other Bindings can be implemented if required. Feel free to do that. I think form our side there is currently no reason to implement another binding than the Browser Binding.
I would suggest to close that issue as it is no issue. We can create a Feature Issue "Add AtomPub Binding" or "Add WebService Binding" if required
