### ISSUE TITLE
upgrade to guzzle 6

### ISSUE THREAD

**Issue by ksjogo** [dkd/php-cmis-client#32]
New TYPO3 and drupal versions require guzzle 6. We are still using guzzle 5 which needs to be upgraded.

**Comment by ksjogo** [comment]
#37

**Comment by ksjogo** [comment]
Done.

**Comment by aWuttig** [comment]
i get many errors with the current master when using guzzle 6 ... do you really change the implementation to use guzzle 6?

**Comment by sascha-egerer** [comment]
> i get many errors with the current master when using guzzle 6 ... do you really change the implementation to use guzzle 6?

What errors?

**Comment by aWuttig** [comment]
my mistake...after upgrade i forget to write readJson() instead of read()
