### ISSUE TITLE
Feature request: Support for Alfresco aspects

### ISSUE THREAD

**Issue by erny** [dkd/php-cmis-client#33]
Although adding alfresco aspects (horizontal inheritance vs vertical inheritance) to alfresco objects is not part of CMIS spec, it would be very interesting to support this feature optionally.

The following features would be great to have:
* Allow to specify aspects during object creation (createDocument, createFolder)
* Getting aspect properties of objects with additional aspects
* Allow updating objects aspect properties.

This feature set is already supported by the python cmislib add-on: "cmislib-alfresco-extension"

https://github.com/pcollardez/cmislib-alfresco-extension

**Comment by erny** [comment]
I'll try to work on this a bit, but it will take some time.

**Comment by NamelessCoder** [comment]
@erny While you work on this, please consider if it would be possible to deliver such aspect support in a separate package - and if necessary add some API to php-cmis-client to make the integration possible. In other words, a solution much like the python cmis add-on for Alfresco. It would be nice to not mix Alfresco-specific features into this generic CMIS library!

**Comment by erny** [comment]
@NamelessCoder Thanks for your suggestions. I'm not a PHP expert, but I will consider it.

**Comment by erny** [comment]
As I was looking through the code I found that only the BROWSER binding seems to be implemented. We've still a lot of old Alfresco 4.0.x around. Although your implementation really looks great, I think I won't be able to use it for what I need for now. Sorry. I'm thinking about closing this issue as "won't fix".

**Comment by erny** [comment]
On the other hand, looking into CMIS 1.1: http://docs.alfresco.com/4.2/pra/1/concepts/cmis-1.1-using-aspects.html

it seems that aspects are exposed through: `cmis:secondaryObjectTypeIds` and this seems to be implemented already.

Closing the ticket. Thanks.

**Comment by NamelessCoder** [comment]
@erny Thanks for following up! Hopefully you can support all your target Alfresco aspect features using secondary types.
