### ISSUE TITLE
The website encountered an unexpected error and Ajax internal error in D8 with Alfresco 5

### ISSUE THREAD

**Issue by selva12** [dkd/php-cmis-client#34]
Hi, I have tried this module with Drupal 8 and Alfresco 5. After configured my connection i clicked the Browse link, it shows the repository details. 
![cmis_browser_drupal_8_list](https://cloud.githubusercontent.com/assets/22187608/23505382/4cad5eea-fef8-11e6-8cca-0ee38b55bac3.png)
But i faces different issues, i will mentioned below one by one.
1. If i click any link its throws the Ajax internal error.
![cmis_browser_drupal_8_ajax](https://cloud.githubusercontent.com/assets/22187608/23505298/def46a06-fef7-11e6-8598-8df38c655802.png)
 2. If i click create folder or document link its shows one form after clicking the submit button it throws  "The website encountered an unexpected error". Error log shows following error.
![cmis_browser_drupal_8_create](https://cloud.githubusercontent.com/assets/22187608/23505641/63487ecc-fef9-11e6-8d3c-9ee4201401dc.png)
![error-details _ drupal 8](https://cloud.githubusercontent.com/assets/22187608/23505370/3e9c780e-fef8-11e6-86f4-5f0dba031247.png)
3. Finally in the connection config what value will give for repository id?
![cmis_connection_drupal_8_rep_id](https://cloud.githubusercontent.com/assets/22187608/23505430/8e3fcdde-fef8-11e6-9229-cc81085c1868.png)

**Comment by ksjogo** [comment]
We (dkd) did not develop/add the D8 integration.
The 500er looks like the drupal code is crashing somehow. Could you check the error log.
Alfresco can have multiple repositories at the same web endpoint. So you should insert the repository id you want to connect to.

**Comment by selva12** [comment]
Hi.. Yeah i checked my error log... Its shows the following error only 
![details_drupal_8_ajx_error](https://cloud.githubusercontent.com/assets/22187608/23544477/0ac6a8e2-ffac-11e6-9f8d-8433a9990d27.png)
Its comming from "**_cmis\vendor\dkd\php-cmis\src\Bindings\Browser\AbstractBrowserBindingService.php_**"

This is my configuration page, i am using drupal 8.2.6 and Alfresco 5 Community Edition 
![edit_test_connection_5 2_drupal_8](https://cloud.githubusercontent.com/assets/22187608/23544611/7b144064-ffac-11e6-913a-1b55005bf089.png)
**_Here i left blank in repository id, because i don't know my repository id. How to find that?_**

**Comment by sascha-egerer** [comment]
@selva12 You can use this example script to list your repositories
https://github.com/dkd/php-cmis-client/blob/master/examples/ListRepositories.php

You have to go to the php-cmis-client folder. Then Copy the template config file in examples/config and adjust it tou your values. After that you can call the script with `php examples/ListRepositories.php`

**Comment by ksjogo** [comment]
We ran into the "invalid form encoding" also with some other project. We will look into that after the upgrade to guzzle 6 as that and/or its interference with guzzle 5 might influence it already.

**Comment by selva12** [comment]
Thankyou for your response. Can u confirm its enough to run the **_composer require "dkd/php-cmis": "^1.0_**"  or  shall we include the folder from **_https://github.com/dkd/php-cmis-client_**?

**Comment by sascha-egerer** [comment]
@selva12 There was no release for a long time so i would suggest to use `composer require dkd/php-cmis:dev-master` for now. And that is basically the same as "using the folder / repository"

**Comment by dj1999** [comment]
The ajax error resolved plese download the drupal module: https://www.drupal.org/project/cmis/releases/8.x-1.x-dev

**Comment by selva12** [comment]
Hi.. @dj1999 
    I have just tried with the updated module which you mentioned above. But the **ajax error not solved**. Its shows the ajax internal error when i clicked the links( please refer my above post). Here i given my db log clearly. Its **throws 2 warnings** also. 
## **Error :**
![invalid_encoding](https://cloud.githubusercontent.com/assets/22187608/23695522/8e7c0894-0394-11e7-83c4-4b7cfcba146a.png)

## **Warnings:**
![missing_arg_1](https://cloud.githubusercontent.com/assets/22187608/23695546/a073714a-0394-11e7-8d29-281ddb6a3ad4.png)
![missing_arg_2](https://cloud.githubusercontent.com/assets/22187608/23695547/a07435f8-0394-11e7-930c-406248a021a8.png)

**Comment by sascha-egerer** [comment]
@selva12 @dj1999 could you please move your discussion to the drupal bugtracker and add a link here for reference?
This issue has nothing to do with this lib AFAICS

**Comment by dj1999** [comment]
@sascha-egerer yes, sure, sorry.
@selva12 https://www.drupal.org/node/2858700

**Comment by NamelessCoder** [comment]
Closing issue - thanks @dj1999 for the reference link!
