### ISSUE TITLE
Dkd\PhpCmis\Exception\CmisConnectionException: Could not fetch repository info! Response is not a valid JSON.

### ISSUE THREAD

**Issue by punambeedkar** [dkd/php-cmis-client#52]
Hi,

Now i am getting this error, while connecting to alfersco 3.4 with drupal 8.2.6 and cmis 2.0
url - http://localhost:8080/alfresco/service/cmis

Alfresco 5.2
Browser binding - will return the data in text/json format
Cmis read that data

Alfresco 3.4
AtomPub or services - will return the data in xml/atom format
Cmis through this error

So cmis latest version will not able to read that format

could you please help me to fix this issue

![cmis_alfresco_3_4](https://cloud.githubusercontent.com/assets/23477184/24443820/c54a8d52-1481-11e7-8c2c-d8937c75fdc2.png)

**Comment by sascha-egerer** [comment]
Alfresco 3.4 is not supported as it does not support Browser Bindings.

**Comment by punambeedkar** [comment]
Hello,

Is there any way to do that as we have to connect drupal 8 with alfresco 3.4 by using cmis.

**Comment by ksjogo** [comment]
Two options:

- You could add/port the atom pub bindings, we do a review and (possibly) merge them. dkd Internet Service Gmbh is not needing the atom pub bindings for any project, so we would not start that on our own. We could talk about sponsoring though, if you have some larger budget remaining.

- Or you use the older drupal cmis extension and port the changes from the 8 version back to it.

**Comment by sascha-egerer** [comment]
Option 3:
* You pay somebody to implement the atom pub bindung for you and contribute it to the php cmis lib
