### ISSUE TITLE
implement getDescendants()

### ISSUE THREAD

**Issue by Selion05** [dkd/php-cmis-client#55]
Hey, 

is this planed in the near future? 

Cheers

**Comment by ksjogo** [comment]
Isn't it already: https://github.com/dkd/php-cmis-client/blob/adc388035767ff972854ddd43fdb005e26212711/src/Bindings/Browser/NavigationService.php#L187 ?

**Comment by Selion05** [comment]
this part is working that's true but in https://github.com/dkd/php-cmis-client/blob/master/src/DataObjects/Folder.php#L529 it isn't which is called from $folder->getDescendants()

**Comment by ksjogo** [comment]
Oh, okay.
We currently have no person working on further development, but are happy to review and merge PRs.
