### ISSUE TITLE
Release version, guzzle 6

### ISSUE THREAD

**Issue by lplume** [dkd/php-cmis-client#60]
Hello,

any plan to release a version with a composer.json updated? afaik the way to install php-cmis-client, with guzzle 6, is to composer require dev-master#1.0.1

Regards

**Comment by kidager** [comment]
Hello,
Any updates on this? I see it's more than a year old now, but it's quite important for this library users, having "dev-master" in a production env is quite risky.

Thanks!

**Comment by ksjogo** [comment]
As the library is not actively maintained, it could be considered quite risky anyway. :D

**Comment by kidager** [comment]
> As the library is not actively maintained, it could be considered quite risky anyway. :D

That's for sure, but having a locked version is always safer.

**Comment by sascha-egerer** [comment]
> ... having "dev-master" in a production env is quite risky.

> That's for sure, but having a locked version is always safer.

@kidager that‘s not really true. The most save way is to lock the package to a commit hash as it can‘t be changed. A version aka Tag can still be force pushed. But this is a bit off topic :-)

We should for sure do a release but I would like to wait until #69 is merged and maybe the other two pull request. Will try to check them in the next days

**Comment by lplume** [comment]
Thank you @sascha-egerer i will look forward to
