### ISSUE TITLE
is it to possible to send a custom http header 

### ISSUE THREAD

**Issue by saurav28** [dkd/php-cmis-client#65]
Hi,

Is it possible to send a custom http header to the requests.

Something like AuthenticationProviders what we have in Java OpenCMIS .

Best Regards,
Saurav

**Comment by sascha-egerer** [comment]
Should be possible. You can define them in the http invoker. See this example
https://github.com/dkd/php-cmis-client/blob/master/examples/CreateFolder.php#L9
and the guzzle documentation http://docs.guzzlephp.org/en/5.3/clients.html

**Comment by saurav28** [comment]
Thanks Sascha for the reply.

And how can i get hold of the response sent back from the request sent ? such that i can fetch a response header being sent from the server .

Best Regards,
Saurav

**Comment by sascha-egerer** [comment]
I would say that this is not possible. Could you please explain why you would need that?

**Comment by saurav28** [comment]
so, i need to connect a CMS server which exposes a csrf token in response header of the first request and then i need to pass this csrf in subsequent calls.

**Comment by saurav28** [comment]
OpenCMIS and PortCMIS provides this through their AuthenticationProvider concept which can be plugged as a session parameter.

https://github.com/apache/chemistry-opencmis/blob/trunk/chemistry-opencmis-commons/chemistry-opencmis-commons-api/src/main/java/org/apache/chemistry/opencmis/commons/spi/AuthenticationProvider.java

**Comment by sascha-egerer** [comment]
@saurav28 You can inject the httpInvoker. I think this is what you need?!
https://github.com/dkd/php-cmis-client/blob/master/examples/CreateDocument.php#L9
