### ISSUE TITLE
Sort cmis result 

### ISSUE THREAD

**Issue by wallon-ines** [dkd/php-cmis-client#76]
Is it to possible to sort cmis result natively in your php libraries ?
eg: I want to sort result by name or CreationDate and if possible show folder first

Best regard

**Comment by NamelessCoder** [comment]
I would say this depends on the exact use case. If you are pulling all objects without pagination you can always use `usort` with a custom sorting function to achieve the result you want. If you need to use pagination then you would be limited to whichever sorting functions are provided by the CMIS service you connected - I would expect any such service to support sorting by creation date, but sorting folders on top may not be universally supported.
