### ISSUE TITLE
cmis:name  encoding character error

### ISSUE THREAD

**Issue by wallon-ines** [dkd/php-cmis-client#77]
I have a problem with charset when upload a document. 

eg: if my document name is `RéàDME.md` in Alfresco I see `RÃ©Ã dme.md`

![Capture d’écran_2020-08-26_17-51-47](https://user-images.githubusercontent.com/11542186/91327057-5a6eb600-e7c5-11ea-9f84-c463c1d89b79.png)

ps: I rework CreateDocument.php for this test

```
    $cid = $session->createObjectId($document->getId());
    echo "Document has been created. Document Id: " . $document->getId() . " Name:" . $session->getObject($cid)->getName() ."\n";
```

**Comment by wallon-ines** [comment]
If I add `_charset_=UTF-8` in form post in my curl request, it's work

How to integrate `_charset_=UTF-8` in this library ?

eg: 
```
curl -X POST    http://locfalhost:8080/alfresco/api/-default-/public/cmis/versions/1.1/browser/root/Shared    -u 'admin:admin'    -H 'content-type: multipart/form-data; charset=utf-8; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW'    -F cmisaction=createDocument    -F 'propertyId[0]=cmis:objectTypeId'    -F 'propertyValue[0]=cmis:document'    -F 'propertyId[1]=cmis:name'    -F 'propertyValue[1]=jàvà_error_in_STUDIO_3456.log'    -F file=@jàvà_error_in_STUDIO_3456.log -F _charset_=UTF-8 | jq
```

**Comment by sascha-egerer** [comment]
@wallon-ines You should be able to define that in the guzzle connection / httpInvoker. 

https://github.com/dkd/php-cmis-client/blob/master/examples/CreateDocument.php#L9-L24

**Comment by lraghib** [comment]
@sascha-egerer could you please explain or provide an example, i'am running with the same issue

**Comment by lraghib** [comment]
@sascha-egerer even if we set the charset like that:
````
 $httpInvoker = new Client(
            [
                'debug' => true,
                'verify' => false,
                'auth'   => [
                    "xxxx",
                    "xxxx",
                ],
                'headers' => [
                    'charset' => 'utf-8'
                ]
                
            ]
        );
````

it doesn't work because this line [AbstractBrowserBindingService.php#L444](https://github.com/dkd/php-cmis-client/blob/245cfdfaf551fddb3605591c74e21d101b813a6a/src/Bindings/Browser/AbstractBrowserBindingService.php#L444 ) changes the header values
