### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by ainsofs** [dkd/php-cmis-client#83]
Does this library run on PHP 8.1? Im getting errors which seem to stem from the League\Url library. Any ideas how to get this working pls? Thnx

`Deprecated function: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in League\Url\Components\AbstractComponent->__toString() (line 67 of /var/www/html/drupal/vendor/league/url/src/Components/AbstractComponent.php)`

**Comment by dkd-dobberkau** [comment]
This library does not provide PHP 8 support. Let me clarify with the main developers if there is a plan for that!

**Comment by ainsofs** [comment]
Thanks that would be help as PHP 7.4 is end of life. I would be happy to assist with upgrade as I need this to upgrade my site to Drupal 10.

**Comment by Aaarrrgggh** [comment]
Hello all,

I try to use the Drupal module phpcmis, which depends on this library. But the library does not work with PHP 8.0. Is there a plan to migrate ? 

Thanks,

Alexander

**Comment by dkd-dobberkau** [comment]
We are open for PR. This Library was funded many years ago by an EU project that has ended. 
There is usage in the Drupal community: Maybe there is a way to coordinate an effort there, too?
