### ISSUE TITLE
Maintain or Abandon this Library

### ISSUE THREAD

**Issue by dkd-dobberkau** [dkd/php-cmis-client#84]
Dear PHP CMIS library users/developers,

We are asking ourselves if we should continue to maintain or start to abandon this Library.
It was built for a project many years ago. In the meantime, PHP has evolved, and we see usage mainly in the Drupal Community.

We are unaware of the amount of work needed to upgrade to PHP 8, and we need more funding within our commercial organization.

Is it possible to hand over the code to someone here?
There are 29 forks and 54 stars on GitHub.

Let us know by commenting below. 

Many thanks in advance, Olivier

**Comment by mrossard** [comment]
I was looking for a CMIS lib for php and this one is pretty much the only "real" result i found...so an installable version would be pretty good to me at least!
In the meantime i'll try taking a look at the code to see if there's a lot of work for this to happen...

**Comment by sascha-egerer** [comment]
The Library has been build on PHP 5 and PHP 7 compatibility has been added later. So I think it’s a lot of work to make it work and a lot of code should be refactored anyways. There is also no active maintenance of the Project since years at all so there are still missing features and there may be unfixed bugs.
Hope this information helps a bit to decide how much time you’ll put into this.

**Comment by mrossard** [comment]
> The Library has been build on PHP 5 and PHP 7 compatibility has been added later. So I think it’s a lot of work to make it work and a lot of code should be refactored anyways. There is also no active maintenance of the Project since years at all so there are still missing features and there may be unfixed bugs. Hope this information helps a bit to decide how much time you’ll put into this.

Well, that's pretty much the conclusion i reached after an hour or so of looking at the code...too much effort to justify doing it for my (very modest) needs. I'll probably use Nuxeo's REST API instead, if that's any help to anyone in a similar situation.

**Comment by darrenoh** [comment]
The Nuxeo REST API that @mrossard referred to is [nuxeo/nuxeo-php-client](https://github.com/nuxeo/nuxeo-php-client).

**Comment by mrossard** [comment]
> The Nuxeo REST API that @mrossard referred to is [nuxeo/nuxeo-php-client](https://github.com/nuxeo/nuxeo-php-client).

Actually it isn't, i just used a simple symfony HttpClient to call the REST API. The client you're linking to is severely outdated and I had multiple compatibility issues when i tried using it.

**Comment by mrossard** [comment]
I mostly needed to upload files, so i pretty much just followed this howto : https://doc.nuxeo.com/nxdoc/howto-upload-file-nuxeo-using-rest-api/

**Comment by dkd-dobberkau** [comment]
As of today, we will archive this repo and put it in read-only mode. Thanks to all who have worked on and used this library.
